Header header
string SSID
string mode
string access_point
float32 frequency
float32 bitrate
float32 tx_power
string sensitivity
string link_quality
int32 signal_level
int32 noise_level
int32 rx_invalid_nwid
int32 rx_invalid_crypt
int32 rx_invalid_frag
int32 tx_excessive_retries
int32 invalid_misc
int32 missed_beacons

# More info about the iwconfig command: http://manpages.ubuntu.com/manpages/bionic/man8/iwconfig.8.html